### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by jochem725** [jochem725/deepdriver#3]
**TODO:**
- [ ] Add modified status led package that doesn’t persist the JSON state
- [ ] Navigation logic (only drive forward)
 - [ ] Start if green light
 - [ ] Stop if yellow/red light
 - [ ] Stop if STOP sign

**Backlog:**
- [ ] Line detection algorithm → Take steering actions based on output
- [ ] OCR on detected signs to set car speed
